"""
Heuristic Fallback Router — processes tool requests WITHOUT Gemini.

When Gemini is unavailable (503 / 429 / quota exhausted) the LLM service
delegates to ``fallback_process_request()`` which:

1. Extracts DOIs from user text and/or attached-document text via regex.
2. Extracts the References section from PDF text via keyword splitting.
3. Determines the user's intent via **semantic embedding similarity**
   (``all-MiniLM-L6-v2``) with keyword matching as a safety-net fallback.
4. Directly executes the appropriate tool and returns a
   ``FunctionCallingResponse`` with template text + rich ``tool_results``
   so the frontend cards render identically to a Gemini-assisted call.

If no intent can be determined, returns ``None`` so the caller can fall
back to the static "AI quá tải" message.
"""

from __future__ import annotations

import logging
import re
import threading
from typing import Any

import numpy as np

logger = logging.getLogger(__name__)

# ── DOI regex (case-insensitive, handles most real-world DOI formats) ────
# Allow parentheses inside DOIs (e.g. Lancet DOIs like S0140-6736(97)11096-0)
_DOI_RE = re.compile(
    r"10\.\d{4,9}/[^\s,;\"'<>\]}>]+",
    re.IGNORECASE,
)

# ── References section splitters (order matters — first match wins) ──────
_REF_SPLIT_PATTERNS: list[re.Pattern] = [
    re.compile(r"\n\s*references?\s*\n", re.IGNORECASE),
    re.compile(r"\n\s*tài\s+liệu\s+tham\s+khảo\s*\n", re.IGNORECASE),
    re.compile(r"\n\s*bibliography\s*\n", re.IGNORECASE),
]

# ── Abstract section extractor ───────────────────────────────────────────
_ABSTRACT_RE = re.compile(
    r"(?:abstract|tóm\s+tắt)\s*[:\-—]?\s*\n?(.*?)(?:\n\s*(?:keywords?|introduction|1[\.\s])|$)",
    re.IGNORECASE | re.DOTALL,
)


# =========================================================================
# Extraction helpers
# =========================================================================

def _extract_dois(text: str) -> list[str]:
    """Return de-duplicated DOIs found in *text*."""
    if not text:
        return []
    # Strip trailing punctuation that regex may over-capture
    raw = _DOI_RE.findall(text)
    cleaned: list[str] = []
    seen: set[str] = set()
    for doi in raw:
        doi = doi.rstrip(".,;:)")
        low = doi.lower()
        if low not in seen:
            seen.add(low)
            cleaned.append(doi)
    return cleaned


def _extract_references_section(text: str) -> str | None:
    """Try to extract the References section from document text."""
    if not text:
        return None
    for pat in _REF_SPLIT_PATTERNS:
        parts = pat.split(text, maxsplit=1)
        if len(parts) >= 2:
            refs = parts[-1].strip()
            if len(refs) > 30:
                return refs
    return None


def _extract_abstract(text: str) -> str | None:
    """Try to extract the Abstract section from document text."""
    if not text:
        return None
    m = _ABSTRACT_RE.search(text)
    if m:
        abstract = m.group(1).strip()
        if len(abstract) > 40:
            return abstract
    # Fallback: first 1500 chars (title + abstract region of most papers)
    if len(text) > 200:
        return text[:1500]
    return None


# =========================================================================
# Intent detection — Semantic Embedding + Keyword Fallback
# =========================================================================

class _Intent:
    RETRACTION = "retraction"
    CITATION = "citation"
    JOURNAL = "journal"
    AI_DETECT = "ai_detect"
    GRAMMAR = "grammar"


# ── Rich semantic descriptions for each intent (used by the ML model) ────
# Multiple example sentences per intent improve embedding coverage.
_INTENT_DESCRIPTIONS: dict[str, str] = {
    _Intent.RETRACTION: (
        "Check if a research paper has been retracted, withdrawn, or has "
        "PubPeer comments, fraud, data manipulation, or scientific misconduct. "
        "Is this paper trustworthy? Has this article been pulled or removed? "
        "Kiểm tra tình trạng rút bài, thu hồi, gian lận học thuật."
    ),
    _Intent.CITATION: (
        "Verify academic citations, reference lists, bibliography entries, "
        "APA/IEEE formatting, and check if sources are real or hallucinated "
        "by AI. Are these references legitimate? Check if sources are made up. "
        "Xác minh trích dẫn, danh sách tham khảo có đúng không."
    ),
    _Intent.JOURNAL: (
        "Recommend, match, or find suitable academic journals to submit "
        "a research paper, manuscript, or abstract. Where should I publish "
        "my research? Which venue is a good fit for my work? "
        "Gợi ý tạp chí phù hợp để nộp bài báo khoa học."
    ),
    _Intent.AI_DETECT: (
        "Detect AI writing, check if text is generated by ChatGPT, GPT, "
        "or other language models. Was this essay written by a machine or "
        "a human? Analyze human vs AI content, check academic integrity. "
        "Phát hiện văn bản do AI viết, kiểm tra xem máy hay người viết."
    ),
    _Intent.GRAMMAR: (
        "Check grammar, fix spelling mistakes, correct typos, proofread "
        "text, improve language flow, edit writing style, fix my sentences, "
        "repair broken English, polish my paragraph, clean up the text. "
        "Kiểm tra ngữ pháp, sửa lỗi chính tả, chỉnh sửa văn bản."
    ),
}

# ── Keyword lists (secondary fallback when ML unavailable / low-conf) ────
_INTENT_KEYWORDS: dict[str, list[str]] = {
    _Intent.RETRACTION: [
        "rút", "retract", "pubpeer", "phốt", "thu hồi",
        "rút bài", "retraction", "bị rút",
    ],
    _Intent.CITATION: [
        "trích dẫn", "citation", "reference", "tham khảo",
        "xác minh", "verify", "kiểm tra trích",
    ],
    _Intent.JOURNAL: [
        "tạp chí", "journal", "nộp bài", "submit", "gợi ý tạp chí",
        "recommend journal",
    ],
    _Intent.AI_DETECT: [
        "ai viết", "ai writing", "phát hiện ai", "detect ai",
        "ai detection", "chatgpt", "gpt viết", "máy viết",
    ],
    _Intent.GRAMMAR: [
        "ngữ pháp", "chính tả", "grammar", "spelling", "typo",
        "sửa lỗi", "lỗi chữ", "spell check", "proofread",
        "kiểm tra lỗi", "chỉnh sửa văn bản",
    ],
}

# Similarity threshold — below this the semantic match is not confident
# enough, and we fall through to keyword matching.
_SEMANTIC_THRESHOLD: float = 0.35


# ── Lazy-loaded Semantic Intent Router (Singleton) ───────────────────────

class SemanticIntentRouter:
    """Encodes user queries with ``all-MiniLM-L6-v2`` and matches them
    against pre-computed intent description embeddings via cosine
    similarity.

    The model is loaded **lazily** on first call to :meth:`classify` so
    it never blocks backend startup.  If ``sentence-transformers`` is not
    installed or the model cannot be loaded, the router degrades
    gracefully and :meth:`classify` returns ``None``.
    """

    _instance: SemanticIntentRouter | None = None
    _lock = threading.Lock()

    def __new__(cls) -> SemanticIntentRouter:
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    inst = super().__new__(cls)
                    inst._model = None  # type: ignore[attr-defined]
                    inst._intent_embeddings: np.ndarray | None = None  # type: ignore[attr-defined]
                    inst._intent_labels: list[str] = []  # type: ignore[attr-defined]
                    inst._init_attempted: bool = False  # type: ignore[attr-defined]
                    cls._instance = inst
        return cls._instance

    # ------------------------------------------------------------------ #
    # Lazy init
    # ------------------------------------------------------------------ #

    def _ensure_model(self) -> bool:
        """Load the sentence-transformer model and pre-compute intent
        embeddings.  Returns ``True`` if ready."""
        if self._model is not None:
            return True
        if self._init_attempted:
            return False  # already failed once — don't retry

        with self._lock:
            if self._model is not None:
                return True
            self._init_attempted = True
            try:
                from sentence_transformers import SentenceTransformer

                logger.info("SemanticIntentRouter: loading all-MiniLM-L6-v2 …")
                self._model = SentenceTransformer("all-MiniLM-L6-v2")

                # Pre-compute intent embeddings
                labels: list[str] = []
                descriptions: list[str] = []
                for intent, desc in _INTENT_DESCRIPTIONS.items():
                    labels.append(intent)
                    descriptions.append(desc)

                self._intent_labels = labels
                self._intent_embeddings = self._model.encode(
                    descriptions, normalize_embeddings=True,
                )
                logger.info(
                    "SemanticIntentRouter ready — %d intents, embedding dim %d.",
                    len(labels),
                    self._intent_embeddings.shape[1],
                )
                return True
            except Exception as exc:
                logger.warning(
                    "SemanticIntentRouter: ML model unavailable — "
                    "falling back to keyword matching. Error: %s",
                    exc,
                )
                self._model = None
                self._intent_embeddings = None
                return False

    # ------------------------------------------------------------------ #
    # Public API
    # ------------------------------------------------------------------ #

    def classify(self, user_text: str) -> tuple[str | None, float]:
        """Return ``(intent, score)`` or ``(None, 0.0)`` if the model is
        unavailable or the confidence is below threshold."""
        if not self._ensure_model():
            return None, 0.0

        try:
            query_emb = self._model.encode(  # type: ignore[union-attr]
                [user_text], normalize_embeddings=True,
            )
            # Cosine similarity (vectors already L2-normalised → dot product)
            similarities = (query_emb @ self._intent_embeddings.T)[0]  # type: ignore[union-attr]
            best_idx = int(np.argmax(similarities))
            best_score = float(similarities[best_idx])
            best_intent = self._intent_labels[best_idx]

            logger.debug(
                "Semantic intent scores: %s | best=%s (%.3f)",
                {l: f"{s:.3f}" for l, s in zip(self._intent_labels, similarities)},
                best_intent,
                best_score,
            )
            return best_intent, best_score
        except Exception as exc:
            logger.warning("SemanticIntentRouter.classify error: %s", exc)
            return None, 0.0


# Module-level singleton (no work done until classify() is called)
_semantic_router = SemanticIntentRouter()


# ── Keyword-based fallback (the original logic) ─────────────────────────

def _keyword_match(user_text: str) -> str | None:
    """Exact keyword matching against ``_INTENT_KEYWORDS``."""
    low = user_text.lower()
    for intent, keywords in _INTENT_KEYWORDS.items():
        for kw in keywords:
            if kw in low:
                return intent
    return None


def _detect_intent(user_text: str, has_doi: bool) -> str | None:
    """Determine user intent using a three-layer strategy:

    1. **Smart defaults** — DOI presence → RETRACTION; long text without
       DOI → AI_DETECT or GRAMMAR based on surface keywords.
    2. **Semantic routing** — encode user text with ``all-MiniLM-L6-v2``
       and compare against intent description embeddings.
    3. **Keyword fallback** — exact substring matching (safety net).
    """
    low = user_text.lower()

    # ── Layer 1: Smart defaults ──────────────────────────────────────
    if has_doi:
        # DOI present — check if another intent is stronger first
        sem_intent, sem_score = _semantic_router.classify(user_text)
        if sem_intent and sem_intent != _Intent.RETRACTION and sem_score >= 0.55:
            # Very confident non-retraction intent even though DOI present
            logger.info(
                "Smart default overridden: DOI present but semantic=%s (%.3f).",
                sem_intent, sem_score,
            )
            return sem_intent
        return _Intent.RETRACTION

    # Long text without DOI → likely AI detection or grammar checking
    text_len = len(user_text.strip())
    if text_len > 350:
        # Check for grammar-related surface hints
        _grammar_hints = {"fix", "sửa", "correct", "proofread", "grammar", "lỗi"}
        if any(h in low for h in _grammar_hints):
            return _Intent.GRAMMAR
        return _Intent.AI_DETECT

    # ── Layer 2: Semantic routing ────────────────────────────────────
    sem_intent, sem_score = _semantic_router.classify(user_text)
    if sem_intent is not None and sem_score >= _SEMANTIC_THRESHOLD:
        logger.info(
            "Semantic intent detected: %s (score=%.3f, threshold=%.2f).",
            sem_intent, sem_score, _SEMANTIC_THRESHOLD,
        )
        return sem_intent

    # ── Layer 3: Keyword fallback ────────────────────────────────────
    kw_intent = _keyword_match(user_text)
    if kw_intent is not None:
        logger.info("Keyword fallback matched intent: %s.", kw_intent)
        return kw_intent

    logger.info("No intent detected (semantic best=%.3f, keyword=None).", sem_score)
    return None


# =========================================================================
# Template response generators
# =========================================================================

def _template_retraction(results: dict) -> str:
    """Generate fallback text for retraction scan results."""
    items = results.get("results", [])
    summary = results.get("summary", {})
    count = len(items)
    retracted = summary.get("retracted", 0)
    concerns = summary.get("has_concern", 0)
    pubpeer = sum(1 for r in items if r.get("pubpeer_comments", 0) > 0)

    lines = [
        "🔍 **(Chế độ dự phòng — Gemini offline)**",
        f"Đã quét **{count}** DOI.",
    ]
    if retracted:
        lines.append(f"⚠️ Phát hiện **{retracted}** bài bị rút bỏ (RETRACTED).")
    if concerns:
        lines.append(f"⚠️ **{concerns}** bài có biểu thức quan ngại (Expression of Concern).")
    if pubpeer:
        lines.append(f"💬 **{pubpeer}** bài có bình luận trên PubPeer.")
    if not retracted and not concerns and not pubpeer:
        lines.append("✅ Không phát hiện vấn đề nghiêm trọng.")
    lines.append("\nXem chi tiết ở bảng kết quả bên dưới.")
    return "\n".join(lines)


def _template_citation(results: dict) -> str:
    """Generate fallback text for citation verification results."""
    items = results.get("results", [])
    stats = results.get("statistics", {})
    total = len(items)
    verified = stats.get("verified", 0)
    not_found = stats.get("not_found", 0)

    lines = [
        "📚 **(Chế độ dự phòng — Gemini offline)**",
        f"Đã kiểm tra **{total}** trích dẫn.",
        f"✅ Xác minh thành công: **{verified}**",
    ]
    if not_found:
        lines.append(f"❌ Không xác minh được: **{not_found}** (có thể do AI ảo giác tạo ra)")
    lines.append("\nXem chi tiết ở bảng kết quả bên dưới.")
    return "\n".join(lines)


def _template_journal(results: dict) -> str:
    """Generate fallback text for journal matching results."""
    journals = results.get("journals", [])
    count = len(journals)
    lines = [
        "📖 **(Chế độ dự phòng — Gemini offline)**",
        f"Tìm thấy **{count}** tạp chí phù hợp.",
    ]
    for i, j in enumerate(journals[:3], 1):
        name = j.get("name", j.get("journal_name", "N/A"))
        score = j.get("similarity_score", j.get("score", j.get("match_score", 0)))
        try:
            score_str = f"{float(score):.1%}"
        except (TypeError, ValueError):
            score_str = str(score)
        lines.append(f"  {i}. {name} (score: {score_str})")
    if count > 3:
        lines.append(f"  … và {count - 3} tạp chí khác.")
    lines.append("\nXem chi tiết ở bảng kết quả bên dưới.")
    return "\n".join(lines)


def _template_ai_detect(results: dict) -> str:
    """Generate fallback text for AI writing detection results."""
    # The AI detector may return the score under different keys
    score = results.get("final_score", results.get("ml_score", results.get("score", 0)))
    try:
        score = float(score)
    except (TypeError, ValueError):
        score = 0.0
    verdict = results.get("verdict", "UNKNOWN")
    lines = [
        "🤖 **(Chế độ dự phòng — Gemini offline)**",
        f"Điểm phát hiện AI: **{score:.1%}**",
        f"Kết luận: **{verdict}**",
    ]
    if score > 0.7:
        lines.append("⚠️ Văn bản có khả năng cao được viết bởi AI.")
    elif score > 0.4:
        lines.append("⚡ Văn bản có dấu hiệu hỗn hợp — cần kiểm tra thêm.")
    else:
        lines.append("✅ Văn bản có vẻ được viết bởi con người.")
    return "\n".join(lines)


def _template_grammar(results: dict) -> str:
    """Generate fallback text for grammar checking results."""
    total = results.get("total_errors", 0)
    error_msg = results.get("error")
    if error_msg:
        return (
            "✍️ **(Chế độ dự phòng — Gemini offline)**\n"
            f"⚠️ Không thể khởi động LanguageTool: {error_msg}"
        )
    lines = [
        "✍️ **(Chế độ dự phòng — Gemini offline)**",
        f"Đã kiểm tra đoạn văn. Phát hiện **{total}** lỗi.",
    ]
    if total == 0:
        lines.append("✅ Không phát hiện lỗi ngữ pháp hay chính tả.")
    else:
        # Show first 5 issues inline
        for i, issue in enumerate(results.get("issues", [])[:5], 1):
            msg = issue.get("message", "")
            replacements = issue.get("replacements", [])
            fix = f" → {replacements[0]}" if replacements else ""
            lines.append(f"  {i}. {msg}{fix}")
        remaining = total - 5
        if remaining > 0:
            lines.append(f"  … và {remaining} lỗi khác.")
        lines.append("\nVui lòng xem văn bản đã sửa bên dưới.")
    return "\n".join(lines)


# =========================================================================
# Public API
# =========================================================================

def fallback_process_request(
    user_text: str,
    file_context: str | None,
) -> dict[str, Any] | None:
    """Attempt to process the user's request using heuristics + direct
    tool execution, bypassing Gemini entirely.

    Returns a dict with keys ``text``, ``message_type``, ``tool_results``,
    ``tool_calls`` — matching the ``FunctionCallingResponse`` fields.
    Returns ``None`` if no intent could be determined.
    """
    combined_text = (user_text or "") + "\n" + (file_context or "")
    dois = _extract_dois(combined_text)
    intent = _detect_intent(user_text or "", has_doi=bool(dois))

    if intent is None:
        logger.info("Heuristic fallback: no intent detected — giving up.")
        return None

    logger.info(
        "Heuristic fallback: intent=%s, dois=%d, has_file=%s",
        intent, len(dois), bool(file_context),
    )

    # ── lazy imports to avoid circular deps at module level ──────────
    from app.services.llm_service import (
        _TOOL_MESSAGE_TYPE,
        _TOOL_DATA_KEY,
        scan_retraction_and_pubpeer,
        verify_citation,
        match_journal,
        detect_ai_writing,
        check_grammar,
        _make_serializable,
    )

    try:
        if intent == _Intent.RETRACTION:
            # Feed DOIs (or full text if no DOIs extracted cleanly)
            input_text = " ".join(dois) if dois else combined_text[:3000]
            tool_name = "scan_retraction_and_pubpeer"
            raw = scan_retraction_and_pubpeer(text=input_text)
            text = _template_retraction(raw)

        elif intent == _Intent.CITATION:
            # Prefer References section; fall back to full text
            refs = _extract_references_section(file_context or "")
            input_text = refs or combined_text[:5000]
            tool_name = "verify_citation"
            raw = verify_citation(text=input_text)
            text = _template_citation(raw)

        elif intent == _Intent.JOURNAL:
            abstract = _extract_abstract(file_context or "")
            input_text = abstract or user_text[:2000]
            tool_name = "match_journal"
            raw = match_journal(abstract=input_text)
            text = _template_journal(raw)

        elif intent == _Intent.AI_DETECT:
            # Use file content if available, otherwise user text
            input_text = (file_context or user_text or "")[:5000]
            if len(input_text.strip()) < 50:
                logger.warning("Fallback AI Detect: text too short (%d chars < 50).", len(input_text.strip()))
                return None
            logger.info("Fallback executing AI Writing Detector (%d chars)...", len(input_text))
            tool_name = "detect_ai_writing"
            raw = detect_ai_writing(text=input_text)
            text = _template_ai_detect(raw)

        elif intent == _Intent.GRAMMAR:
            input_text = (file_context or user_text or "")[:10000]
            if len(input_text.strip()) < 10:
                logger.warning("Fallback Grammar: text too short (%d chars).", len(input_text.strip()))
                return None
            logger.info("Fallback executing Grammar Checker (%d chars)...", len(input_text))
            tool_name = "check_grammar"
            raw = check_grammar(text=input_text)
            raw = _make_serializable(raw)
            text = _template_grammar(raw)

        else:
            return None

    except Exception as exc:
        logger.error("Heuristic fallback tool execution failed: %s", exc, exc_info=True)
        return None

    # Build response matching FunctionCallingResponse structure
    mt = _TOOL_MESSAGE_TYPE.get(tool_name)
    msg_type = mt.value if mt else "text"
    data_key = _TOOL_DATA_KEY.get(tool_name, "")
    tool_results = {
        "type": msg_type,
        "data": raw.get(data_key, raw) if data_key else raw,
    }

    return {
        "text": text,
        "message_type": msg_type,
        "tool_results": tool_results,
        "tool_calls": [{
            "name": tool_name,
            "args": {"text": input_text[:200] + "..." if len(input_text) > 200 else input_text},
            "result": raw,
        }],
    }
