from .formatters import build_completed_metadata, build_csl_json, format_apa_reference, format_bibtex
from .models import CandidateWork, CitationCheckResult, MetadataMatchResult, ReferenceMetadata
from .normalize import normalize_author_for_citation, normalize_author_name, normalize_doi, normalize_title, normalize_venue
from .parser import build_fallback_title_query, extract_authors, parse_reference_metadata
from .scoring import (
    LOW_PARSE_CONFIDENCE,
    SOURCE_ERROR_STATES,
    build_match_reason,
    candidate_has_incomplete_metadata,
    candidate_missing_fields,
    choose_best_match,
    compare_reference_to_candidate,
    has_source_conflict,
    metadata_consistency_from_field_evidence,
    score_candidate,
    top_source_candidate,
)
from .sources import (
    CrossrefSource,
    DataCiteSource,
    OpenAlexSource,
    PublisherMetaSource,
    SemanticScholarSource,
    normalize_crossref_work,
    normalize_datacite_work,
    normalize_openalex_work,
    normalize_semantic_scholar_paper,
)

__all__ = [
    "CandidateWork",
    "CitationCheckResult",
    "MetadataMatchResult",
    "ReferenceMetadata",
    "LOW_PARSE_CONFIDENCE",
    "SOURCE_ERROR_STATES",
    "build_completed_metadata",
    "build_csl_json",
    "build_fallback_title_query",
    "build_match_reason",
    "candidate_has_incomplete_metadata",
    "candidate_missing_fields",
    "choose_best_match",
    "compare_reference_to_candidate",
    "extract_authors",
    "format_apa_reference",
    "format_bibtex",
    "has_source_conflict",
    "metadata_consistency_from_field_evidence",
    "normalize_author_for_citation",
    "normalize_author_name",
    "normalize_crossref_work",
    "normalize_datacite_work",
    "normalize_doi",
    "normalize_openalex_work",
    "normalize_semantic_scholar_paper",
    "normalize_title",
    "normalize_venue",
    "parse_reference_metadata",
    "score_candidate",
    "top_source_candidate",
    "CrossrefSource",
    "DataCiteSource",
    "OpenAlexSource",
    "PublisherMetaSource",
    "SemanticScholarSource",
]
